# Generated by Django 3.2.16 on 2023-01-12 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albumShare', '0002_photo_album_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='created_by',
            new_name='user',
        ),
    ]
