# Generated by Django 3.2.16 on 2023-01-12 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albumShare', '0003_rename_created_by_album_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover_photo_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='albumShare.album'),
        ),
    ]
