# Generated by Django 3.2.16 on 2023-01-12 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albumShare', '0005_photo_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='cover_photo_id',
        ),
        migrations.AddField(
            model_name='album',
            name='cover_photo_url',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
